[Feature] Add AutoSuggestion option for TextBox
MaterialDesignInXAML/MaterialDesignInXamlToolkit pull request #3207
Opened 2023-05-20 19:12 UTC by AbderrahmaneAhmam

### Description:
Hello everyone,

This pull request introduces a new feature to the MaterialDesignInXamlToolkit project, enabling the AutoSuggestion option for the TextBox control. This feature enhances user experience by providing automatic suggestions as the user types. The search algorithm is controlled by the developer in the ViewModel part, making it customizable and flexible.

### Key Changes:

- Added AutoSuggestionEnabled property to the TextFieldAssist.
- Added AutoSuggestionItemsSource property to the TextFieldAssist.
- Added AutoSuggestionItemTemplate property to the TextFieldAssist.
- Added AutoSuggestionItemTemplateSelector property to the TextFieldAssist.
- Added AutoSuggestionValueMember property to the TextFieldAssist.
- Added AutoSuggestionDisplayMember property to the TextFieldAssist.

This contribution aligns with the MaterialDesignInXamlToolkit project's goals of providing modern and user-friendly UI components. As a first-time contributor to an open source project, I am thrilled to be a part of this community and contribute to its growth. I would greatly appreciate any feedback and guidance to improve the feature and align it with the project's standards.

I have thoroughly tested the feature and ensured it seamlessly integrates with the existing codebase. I'm excited about this contribution and believe it will be valuable for the project's users.

I'm looking forward to your feedback and the opportunity to collaborate on further enhancing this feature.

Please let me know if there are any remarks or changes you would like me to make.

### Screenshots & Demo
![Demo_AutoSuggestion_AdobeExpress](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/48412593/31b62be8-aa4b-4b50-8148-3849aebb682c)

2023-05-22 05:50 UTC, Keboo requested changes
Hi @AbderrahmaneAhmam

Thank you for this. I think this would be a nice addition as there have been requests for something similar in the past. 

A few suggestions before we merge it. 
1) I think this would be better as a new control that derives from TextBox, rather than adding a bunch of attached properties. This would move all of the attached properties into dependency properties on the new control. 
2) This will likely mean duplicating the existing TextBox Styles/Templates to target the new control type.
3) I think doing this would allow for a cleaner setup. The needed setup right now needing the register for the TextChanged to show the drop down is a bit awkward to use. With a custom control, it would be able to register its own TextChanged event handler to manage showing the list.

Again, good work so far.

2023-05-22 09:21 UTC, AbderrahmaneAhmam commented on MainDemo.Wpf/Domain/FieldsViewModel.cs
> +        }
Thanks for your reply.
Is it acceptable to duplicate all the styles of the TextBox to be reused in the custom control? If so, please provide a suggestion for the name of the custom control. Additionally, for the TextChanged event, I propose extracting it as a command. This approach allows for better control of the search algorithm through the ViewModel.

2023-05-22 16:20 UTC, AbderrahmaneAhmam commented on MainDemo.Wpf/Domain/FieldsViewModel.cs
> +        }
Thanks @Keboo. That's clear. I will start working on this task and try to finish it as soon as possible.

2023-05-22 17:27 UTC, Keboo commented on MainDemo.Wpf/Domain/FieldsViewModel.cs
> +        }
Feel free to reach out if you have questions. I really appreciate the help and look forward to it.

2023-06-19 08:54 UTC, AbderrahmaneAhmam commented on MainDemo.Wpf/Domain/FieldsViewModel.cs
> +        }
Hello @Keboo ,

I have implemented this approach. Could you please verify if any adjustments or modifications are needed? I have not yet completed the testing phase, and for testing purposes, I have used the same file "Fields.Xaml". I am unsure if we need to create a separate page for this new control.

Thank you for your assistance.

2023-08-12 19:23 UTC, AbderrahmaneAhmam commented
Hello @Keboo,

I am currently working on the TODOs, but I am having difficulty understanding this specific part:
"TODO: Test case with ICollectionSource." Could you please provide some clarification?

2023-08-13 05:27 UTC, Keboo commented
> Hello @Keboo,
> 
> I am currently working on the TODOs, but I am having difficulty understanding this specific part: "TODO: Test case with ICollectionSource." Could you please provide some clarification?

Great. Sorry for just jumping in and doing some work on it, kinda got a little over excited and I knew my recent file-scope namespace all the things was going to cause conflicts. 


For the `ICollectionView` I have pushed another commit that shows what I was thinking (the test is currently failing).
I suspect that to get the selection working, we may end up needing to make the base class `Selector` and then add additional properties to support the normal TextBox behavior (In this case I think the behavior of this control may be closer to a `ComboBox` than a `TextBox`).

2023-08-14 13:50 UTC, AbderrahmaneAhmam commented
> > Hello @Keboo,
> > I am currently working on the TODOs, but I am having difficulty understanding this specific part: "TODO: Test case with ICollectionSource." Could you please provide some clarification?
> 
> Great. Sorry for just jumping in and doing some work on it, kinda got a little over excited and I knew my recent file-scope namespace all the things was going to cause conflicts.
> 
> For the `ICollectionView` I have pushed another commit that shows what I was thinking (the test is currently failing). I suspect that to get the selection working, we may end up needing to make the base class `Selector` and then add additional properties to support the normal TextBox behavior (In this case I think the behavior of this control may be closer to a `ComboBox` than a `TextBox`).

Hi @Keboo 

Currently, we have the capability to extract these properties from the ListBox utilized within this control. The principle behind this is to construct a control similar to a TextBox, enabling its use alongside other TextBox features. The sole distinguishing feature is the auto-suggestion functionality.

I've conducted research on similar controls, and they function using a similar approach. The base class is a TextBox. For instance, let's consider Syncfusion's [Autocomplete](https://help.syncfusion.com/wpf/autocomplete/getting-started): the base class of SfTextBoxExt is a TextBox. However, it offers additional features like SelectedItem and other properties from the Selector class.


```csharp
public class SfTextBoxExt : TextBox, IDisposable, ITextInputLayoutSelector
```

```csharp
public object SelectedItem { get; set; }
public IEnumerable SelectedItems { get; set; }
public object SelectedValue { get; set; }
```

2023-08-14 19:16 UTC, AbderrahmaneAhmam commented
Hi @Keboo,

sorry, I understand now what you are referring to with "IsSynchronizedWithCurrentItem". To be honest, I haven't used it before, but after doing some research, I've gained a better understanding. I have a suggestion: how about enabling it by default in the ListBox of AutoSuggestBox? This would allow us to use it for keyboard navigation through ICollectionView. Additionally, this option would be available for consumers as well.

2023-08-16 06:43 UTC, Keboo commented
> Hi @Keboo,
> 
> sorry, I understand now what you are referring to with "IsSynchronizedWithCurrentItem". To be honest, I haven't used it before, but after doing some research, I've gained a better understanding. I have a suggestion: how about enabling it by default in the ListBox of AutoSuggestBox? This would allow us to use it for keyboard navigation through ICollectionView. Additionally, this option would be available for consumers as well.

I think that would be a good idea.

2023-09-05 16:14 UTC, anno0 commented
Will it be possible to use it in a RichTextBox?

2023-09-16 19:44 UTC, AbderrahmaneAhmam commented
> Will it be possible to use it in a RichTextBox?

Actually, this pull request is not related to the RichTextBox; it's about creating a new control, the AutoSuggestBox.

2023-09-21 03:45 UTC, Keboo approved these changes

2023-09-21 03:45 UTC, merged